DROP SEQUENCE memberseq;
DROP TABLE member;


CREATE SEQUENCE memberseq;
--멤버 번호, 아이디, 패스워드, 이름, 주소, 전화번호, 이메일, 가입여부, 등급
-- 가입여부(Y-가입,N-탈퇴), 등급
CREATE TABLE MEMBER(
	mbNO NUMBER NOT NULL,
	mbID VARCHAR2(500) NOT NULL,
	mbPW VARCHAR2(500) NOT NULL,
	mbNAME VARCHAR2(500) NOT NULL,
	mbADDR VARCHAR2(4000) NOT NULL,
	mbPHONE VARCHAR2(20) NOT NULL,
	mbEMAIL VARCHAR2(100) NOT NULL,
	mbENABLED VARCHAR2(2) NOT NULL,
	mbROLE VARCHAR2(100) NOT NULL,
	CONSTRAINT MEMBER_PK PRIMARY KEY(mbNO),
	CONSTRAINT MEMBER_UQ_ID UNIQUE(mbID),
	CONSTRAINT MEMBER_UQ_PHONE UNIQUE(mbPHONE),
	CONSTRAINT MEMBER_UQ_EMAIL UNIQUE(mbEMAIL),
	CONSTRAINT MEMBER_CHK_ENABLED CHECK(mbENABLED IN ('Y','N'))
);

INSERT INTO member VALUES (MEMBERSEQ.NEXTVAL, 'admin', '1234', '관리자', '경기도 용인시 기흥구', '010-1234-1234', 'SASUMPI123@NAVER.COM', 'Y', 'ADMIN');
INSERT INTO member VALUES (MEMBERSEQ.NEXTVAL, '1234', '1234', '회원', '경기도 용인시 기흥구', '010-1234-1235', 'SASUMPI1235@NAVER.COM', 'Y', 'asdf');



SELECT * FROM MEMBER;

UPDATE MEMBER SET mbENABLED = 'N' WHERE mbNO = 16;

commit;