CREATE SEQUENCE MVCSEQ;
CREATE TABLE MVCBOARD(
	MYNO NUMBER PRIMARY KEY,
	MYWRITER VARCHAR2(1000) NOT NULL,
	MYTITLE VARCHAR2(2000) NOT NULL,
	MYCONTENT VARCHAR2(4000) NOT NULL,
	MYDATE DATE NOT NULL)
DROP TABLE MVCBOARD;
	

INSERT INTO MVCBOARD VALUES(MVCSEQ.NEXTVAL, '관리자', 'TEST제목', 'TEST내용', SYSDATE);

SELECT * FROM MVCBOARD;