drop table member;
CREATE TABLE MEMBER(
MEMBER_NUM NUMBER NOT NULL,
MEMBER_ID VARCHAR2(100) PRIMARY KEY,
MEMBER_PASSWORD VARCHAR2(100) NOT NULL
)
CREATE sequence memberseq;

insert into MEMBER VALUES(MEMBERSEQ.NEXTVAL, '1234','1234');

SELECT * from member;


create table myboard(
	MYNO NUMBER PRIMARY KEY,
	MYNAME VARCHAR2(1000) NOT NULL,
	MYTITLE VARCHAR2(2000) NOT NULL,
	MYCONTENT VARCHAR2(4000) NOT NULL,
	MYDATE DATE NOT NULL
)
CREATE sequence myseq;


